### ISSUE TITLE
Error could not fin source directory

### ISSUE THREAD

**Issue by Micromot20** [shpi/hypertouch40#2]
when im using the command 

> sudo dkms install hypertouch40/1.0

i get the error

> Error! could not find module source directory
Directory: /usr/src/hypertouch40-1.0 does not exist

**Comment by tanno1** [comment]
I am having this same issue^

**Comment by tanno1** [comment]
Hello @Micromot20 I just had the same error and I figured it out. Do you still need assistance?
For anyone in the future that might run into this error (I am building a LMN-3 synth and I ran into this error so if anyone is here from Floyd Steinbergs channel, whats up!) the issue comes from the following:
`sudo ln -s /home/**pi**/hypertouch40 /usr/src/hypertouch40-1.0` if you used a different name for your raspberry pi, then you must replace the bolded **pi** with the name. If you have already made a link with this error, you will need to remove it. To do so use the following:
`sudo rm /usr/src/hypertouch40-1.0`
